import { ORDER_STATUS } from '../../../../entities/orderBase.entity';

export const OrdersCustomReportMapper = {
    general: {
        importedOrderId: '"order"."id" as "Imported Order Id"',
        systemOrderId: '"order"."id" as "System Order Id"',
        cargo: 'array_to_string(array_agg(concat("car"."year", \' \', "car"."make", \' \', "car"."model")), \'|\') as "Cargo"',
        vinNumbers: 'array_to_string(array_agg("car"."vin"), \'|\')  as "Vin Numbers"',
        creationDate: 'to_char(DATE("order"."createdAt"), \'DD/MM/YYYY\') as "Creation Date"',
    },
    pickupInfo: {
        date: '"order"."pickDate" as "Pickup Date"',
        name: 'CONCAT("sender"."firstName", \' \', "sender"."lastName") as "Sender Name"',
        address: '"pickLocation"."address" as "Pickup Address"',
        city: '"pickLocation"."city" as "Pickup City"',
        state: '"pickLocation"."state" as "Pickup State"',
        zipCode: '"pickLocation"."zipCode" as "Pickup Zip Code"',
        phone: '"sender"."phoneNumber" as "Sender Phone"',
        email: '"sender"."email" as "Sender Email"',
    },
    deliveryInfo: {
        date: '"order"."deliveryDate" as "Delivery Date"',
        name: 'CONCAT("receiver"."firstName", \' \', "receiver"."lastName") as "Receiver Name"',
        address: '"deliveryLocation"."address" as "Delivery Address"',
        city: '"deliveryLocation"."city" as "Delivery City"',
        state: '"deliveryLocation"."state" as "Delivery State"',
        zipCode: '"deliveryLocation"."zipCode" as "Delivery Zip Code"',
        phone: '"receiver"."phoneNumber" as "Receiver Phone"',
        email: '"receiver"."email" as "Receiver Email"',
    },
    shipperInfo: {
        name: '"shipper"."fullName" as "Shipper Name"',
        address: '"shipper"."address" as "Shipper Address"',
        city: '"shipper"."city" as "Shipper City"',
        state: '"shipper"."state" as "Shipper State"',
        zipCode: '"shipper"."zipCode" as "Shipper Zip Code"',
        phone: '"shipper"."phone" as "Shipper Phone"',
        email: '"shipper"."email" as "Shipper Email"',
    },
    paymentInfo: {
        terms: '"order"."paymentNote" as "Payment Terms"',
        // tslint:disable-next-line: max-line-length
        status: `CASE WHEN "order"."status"='${ORDER_STATUS.PAID}' THEN 'paid' WHEN "order"."invoiceUrl" IS NOT NULL THEN 'invoiced' END as "Payment Status"`,
        amount: '"order"."salePrice" as "Payment Amount"',
        brokerFee: '"order"."brokerFee" as "Broker Fee"',
        method: '"order"."paymentMethods" as "Payment Method"',
    },
};

export const OrdersCustomReportOrderByMapper = {
    importedOrderId: '"Imported Order Id"',
    systemOrderId: '"System Order Id"',
    cargo: '"Cargo"',
    vinNumbers: '"Vin Numbers"',
    creationDate: '"Creation Date"',
    pickupDate: '"Pickup Date"',
    pickupName: '"Sender Name"',
    pickupAddress: '"Pickup Address"',
    pickupCity: '"Pickup City"',
    pickupState: '"Pickup State"',
    pickupZipCode: '"Pickup Zip Code"',
    pickupPhone: '"Sender Phone"',
    pickupEmail: '"Sender Email"',
    deliveryDate: '"Delivery Date"',
    deliveryName: '"Receiver Name"',
    deliveryAddress: '"Delivery Address"',
    deliveryCity: '"Delivery City"',
    deliveryState: '"Delivery State"',
    deliveryZipCode: '"Delivery Zip Code"',
    deliveryPhone: '"Receiver Phone"',
    deliveryEmail: '"Receiver Email"',
    shipperDate: '"Shipper Date"',
    shipperName: '"Shipper Name"',
    shipperAddress: '"Shipper Address"',
    shipperCity: '"Shipper City"',
    shipperState: '"Shipper State"',
    shipperZipCode: '"Shipper Zip Code"',
    shipperPhone: '"Shipper Phone"',
    shipperEmail: '"Shipper Email"',
    paymentTerms: '"Payment Terms"',
    paymentStatus: '"Payment Status"',
    paymentAmount: '"Payment Amount"',
    paymentBrokerFee: '"Broker Fee"',
    paymentMethod: '"Payment Method"',
};
