version: "3"
services:
  test_db:
    image: kartoza/postgis:11.0-2.5
    volumes:
      - ${DB_VOLUME-/data/pgis}:/var/lib/postgresql
    env_file: ./env/test.env
    ports:
      - "5432:5432"
    restart: on-failure
